# Generated by Django 5.2.5 on 2025-12-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pergunta',
            field=models.CharField(max_length=500),
        ),
    ]
