# Generated by Django 5.2.5 on 2025-09-23 01:06

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[authentication.validators.validate_cpf], verbose_name='CPF'),
        ),
    ]

