# Generated by Django 5.2.5 on 2025-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bairro_customuser_cidade_customuser_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
