# Generated by Django 5.2.5 on 2025-12-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_cep_alter_customuser_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionário'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
