# Generated by Django 5.2.5 on 2025-12-30 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(default='fas fa-folder', max_length=50, verbose_name='Ícone FontAwesome')),
                ('cor_gradiente', models.CharField(default='linear-gradient(135deg, #00A6FF, #0056b3)', max_length=100, verbose_name='Cor Gradiente CSS')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo HTML')),
                ('tipo', models.CharField(choices=[('tutorial', 'Tutorial'), ('guia', 'Guia'), ('faq', 'FAQ')], default='tutorial', max_length=20, verbose_name='Tipo')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Tags (separadas por vírgula)')),
                ('tempo_leitura', models.IntegerField(default=5, verbose_name='Tempo de Leitura (min)')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('avaliacoes_positivas', models.IntegerField(default=0, verbose_name='Avaliações Positivas')),
                ('avaliacoes_negativas', models.IntegerField(default=0, verbose_name='Avaliações Negativas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='menu.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('util', models.BooleanField(verbose_name='Foi Útil?')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário (opcional)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='menu.artigo', verbose_name='Artigo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação de Artigo',
                'verbose_name_plural': 'Avaliações de Artigos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
