# Generated by Django 5.2.5 on 2026-01-03 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='avaliacoes_negativas',
            field=models.PositiveIntegerField(default=0, verbose_name='Avaliações Negativas'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='avaliacoes_positivas',
            field=models.PositiveIntegerField(default=0, verbose_name='Avaliações Positivas'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='destaque',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tags (separadas por vírgula)'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='tempo_leitura',
            field=models.PositiveIntegerField(default=5, verbose_name='Tempo de Leitura (min)'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='tipo',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('guia', 'Guia'), ('faq', 'FAQ')], db_index=True, default='tutorial', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='visualizacoes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='avaliacaoartigo',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_detalhadas', to='menu.artigo', verbose_name='Artigo'),
        ),
        migrations.AlterField(
            model_name='avaliacaoartigo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ordem',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoartigo',
            unique_together={('artigo', 'session_key'), ('artigo', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['ativo', 'destaque'], name='menu_artigo_ativo_aed728_idx'),
        ),
        migrations.AddIndex(
            model_name='artigo',
            index=models.Index(fields=['categoria', 'ativo'], name='menu_artigo_categor_4fc285_idx'),
        ),
        migrations.AlterModelTable(
            name='artigo',
            table='menu_artigo',
        ),
        migrations.AlterModelTable(
            name='avaliacaoartigo',
            table='menu_avaliacao_artigo',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='menu_categoria',
        ),
    ]
