# Generated by Django 5.2.5 on 2025-12-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_ativos_relacionados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-data_criacao'], 'permissions': [('atribuir_ticket', 'Pode atribuir tickets a funcionários')], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
